version: "1.0"
info:
  model: int-scaffold
packages:
- name: MirsWorkspace2Project
  gitServerName: MirsGIT
  gitUrl: https://github.com/mirhussainali/MirsWorkspace2Project
  gitUsername: mirhussainali
  gitBranch: main
- name: DellPOC
  gitServerName: MirsGIT
  gitUrl: https://github.com/mirhussainali
  gitUsername: mirhussainali
  gitBranch: main
services:
- serviceName: project.mirsworkspace2.integrations:EdgeFlow
  packages:
  - name: MirsWorkspace2Project
    version: "1.0"
- serviceName: pub.date:getCurrentDateString
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.mirsworkspace2.integrations:EdgeFlowChild1
  packages:
  - name: MirsWorkspace2Project
    version: "1.0"
- serviceName: project.mirsworkspace2.integrations:EdgeFlow_ProcessMsg
  packages:
  - name: MirsWorkspace2Project
    version: "1.0"
  - name: DellPOC
    version: "1.0"
- serviceName: DellEdgeServices.FlowServices:SendToRMQ
  packages:
  - name: DellPOC
    version: "1.0"
- serviceName: pub.jms:send
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.flow:getLastError
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
